### ISSUE TITLE
提示python已停止工作

### ISSUE THREAD

**Issue by welaing** [ekils/dannyAVgleDownloader#1]
开始生成文件时，提示停止工作，请指教![get_failure](https://user-images.githubusercontent.com/30540648/34317557-8bedc076-e7ec-11e7-924c-00d54ecd1804.jpg)

**Comment by ekils** [comment]
可以把error code 放上來看看嗎？
我在昨天之前都能用的。今天avgle似乎有增加廣告遮蔽功能，我需要再改版一次針對該問題修改。

**Comment by kaliludan** [comment]
Traceback (most recent call last):
  File "/Users/********/my-project/dannyAVgleDownloader-master/main.py", line 143, in run
    file = requests.get(videopath)
  File "/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
