### ISSUE TITLE
No such file or directory: '/usr/local/Cellar/phantomjs/2.1.1/bin/phantomjs'

### ISSUE THREAD

**Issue by adrhe** [ekils/dannyAVgleDownloader#2]
运行时出现这个问题：
我的环境是python3.7, macos 10.14.2:

ADRHE-M-J0JZ:dannyAVgleDownloader adrhe$ python main.py
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**_FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/phantomjs/2.1.1/bin/phantomjs': '/usr/local/Cellar/phantomjs/2.1.1/bin/phantomjs'_**

**Comment by adrhe** [comment]
不知道大大还有没有在维护这个项目：）

**Comment by ekils** [comment]
沒有咧，因為它廣告太多，修改麻煩，我後來就不抓那網站的了。抱歉

從我的 iPhone 傳送

Chuan <notifications@github.com<mailto:notifications@github.com>> 於 2018年12月24日 上午11:53 寫道：


不知道大大还有没有在维护这个项目：）
